services:
  profile:
    build: .
    image: ${REGISTRY}/hotel_app_profile_single_node_memdb
    container_name: 'hotel_app_profile'
    entrypoint: profile
    ports:
      - "8081"
    restart: always
  nginx:
    image: nginx:1.20.0
    container_name: nginx
    ports:
      - "8581:8581"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro