version: "3"
services:
  profile:
    image: hvolos01/hotel_app_profile_single_node_memdb
    container_name: 'hotel_app_profile'
    entrypoint: profile
    ports:
      - "8081"
    restart: always

  nginx:
    image: nginx:1.20.0
    container_name: nginx
    ports:
      - "8581:8581"
    volumes:
      - /users/ntheod10/cs499-fa22/assignments/hw4/conf/nginx.conf:/etc/nginx/nginx.conf:ro